name: wine
channels:
  - conda-forge
dependencies:
  - python=3.11
  - setuptools<65
  - pip
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - ipykernel
  - pytest
  - pip:
      - dvc
      - dvc-gdrive
      - kedro
      - kedro-datasets
      - kedro-mlflow
      - mlflow
      - pycaret>=3.3.0
      - optuna
      - optuna-integration[sklearn]
      - feast>=0.37.0
      - flask
      - evidently
      - xgboost
      - lightgbm
